# Generated by Django 5.1.1 on 2024-11-01 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('regiao', models.CharField(blank=True, max_length=100, null=True)),
                ('treinador', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_jogadores', models.IntegerField(blank=True, default=0, null=True)),
                ('vitorias', models.IntegerField(blank=True, default=0, null=True)),
                ('derrotas', models.IntegerField(blank=True, default=0, null=True)),
                ('campeonatos_vencidos', models.IntegerField(blank=True, default=0, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('posicao', models.CharField(blank=True, choices=[('PG', 'Armador'), ('SG', 'Ala-Armador'), ('SF', 'Ala'), ('PF', 'Ala-Pivô'), ('C', 'Pivô')], max_length=2, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('pontos', models.IntegerField(blank=True, default=0, null=True)),
                ('rebotes', models.IntegerField(blank=True, default=0, null=True)),
                ('assistencias', models.IntegerField(blank=True, default=0, null=True)),
                ('turnovers', models.IntegerField(blank=True, default=0, null=True)),
                ('roubos_bola', models.IntegerField(blank=True, default=0, null=True)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores', to='times.time')),
            ],
        ),
    ]
